apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:f8CJ2tkaj4vOOZovSa6lo0Mvmf7zlp+4Ri9Y7AyMurNSSEI+jdZ/HxokOI8wRmcP9W1eDxgOgVoFjZMq,iv:oJu5Y1erDEbjwBdSB/ROqSWM9w6JMloM14FF/+VZBWg=,tag:0OV+AW6JUOtKE2ToRUcrpA==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:3MVGx2cwn6VloJERrMK3TILhViB7xpJJxXdS9Ge+/28=,iv:1Cwxe8ZBUOoRiLzDmTjg/LEm82UTFM0py5N++NiboEs=,tag:VF/VPhC7EV8oCl0R1sJWxg==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:aC0CwB42N99MWfzx79gNsSnMn36Du6VberMramfEA2U1UUx5kfUDjOm8eoaRoVDrCgqr/Ag6Ege9IrZ8,iv:uYdSir2W3V5ocouY6sWCQcACBdHCefqliGUltNCb5DQ=,tag:zAKqA2cSQywTuaxtQnZ9tg==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQzI3RU01THM4UmoybjFU
            TTl0SzN6RTdUb1JVVmcrY1RhekdoeGNFUUU4ClQxWFhMWDRVb25PRXZVRmk4dEUr
            WGp5cksxZ1BJbTE3eldRVEJSY2VYRDQKLS0tIE12N1pUR0ttMkE1TTZtWWxuTjBa
            VFQ1QVZUb0dtWUg1NStXVm1WRWdiVTAK3+f5XPnMlfdJtCOIdwciw4pRNvR7fnZ4
            dlGHtmvWk5SW3weJJnFSH/AiUwrx1QDB2EfiDRvj/tsF4MHOQ4todw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T16:44:51Z"
    mac: ENC[AES256_GCM,data:cfSU8QbgNDWnAj520CFo/CHKzH4c52RfZvke1tFqTmUuDeS/4e63PQQS7XNur9OjyMzwdGLZqEZcv9GNQ4IqE8mMGS6WJtHWT7dHauGPKwHu9HDRxQE8B5BQ1Jc0tRbC1EqZM5LOU84QKeXkCZUwpl/SJAsxV/Xvr9u5KLV+yrE=,iv:F65GkSTzAeADqXwotkUF+lUjLIvFEjoSy9wj6m9yKb8=,tag:oQ/XD79Br/KagVtuvnF1dQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
