---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - hashicorp.yaml
  - metallb.yaml
  - prometheus-community.yaml
  - rook-release.yaml
