apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: litellm
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Mq+P9guhHlRNsRknvsLBwG6SnN1rHzQ+3eoJ+NYJCA6N0aCXH5UufXDoXNmUt8B2z2nO6zZZB6e/6bsIpojtZq3Wu+jFLrI3xMU8iARR8r2CkV+6QrArOpjVKKCir6mjvJiWokoc2JtSY+5k,iv:aMWzXw8LBCmI3tEujJS2CNuCkZVs1DrIjFV0XiPN9kc=,tag:/B9qR+mNTHVAEw/Zj6GOXA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:TpnMgVDv/Af0860YQjITAqvjttuQV0FCwQLXQekMqLjGkhvP2QqLe/b0++k5Whod13Pczg6dve1I1NtpT24ry51c5g==,iv:3uDqL+xGTEBVA8oXVCoqJy4IRWhAJdd8dFvxaEpnMn4=,tag:eg3AkWapliJMy8cl4qxMlQ==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNXlXaTlWSUNSWDN4OU04
            ZWhTZzVHRnZwelpMRWNjb0s5VnQxSnVKc1IwCkFxS2lRRWxTb3Joclh3SG93dU82
            M1R2T2FkS2Y1MzFVdnFndlI1MXhVaFUKLS0tIGs0bUFLbUJBZDQ0YzNKZTZ2RENL
            eldnZ09rQlRCbEVjRXNUUmZ6d2VZblEKVfSmpLtAe6FMMQRO0d2jeYOd6VCn5Dbx
            9Sx+21YURibzXQMoMGXvEI8J9uGVrMMzXucNCvZ2VWnbm2YVfY+ieQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T18:22:42Z"
    mac: ENC[AES256_GCM,data:l7d/gBNXzvTKRRbDcBdp6PII5+cOs93uR3M+MVXc/+7HsmLc17lnUUKmHdB0eUs96PxryIecNrZcyssrUUyXIteGVlVbbPHnPbhVlyx8JZKb4AWMtnXoSctHUIfRYQ6KvlBzzBpVxzzRG1owoIqfV8TR0E0t2pZDEULwyzmwOwY=,iv:9ZGXjfkjshEsNTXRDvB79kebp8t1Z8kXd3CsmaDCzGA=,tag:Bn23J01QG0oOM7JAj0EI8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
