apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: litellm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:A8H+vgbIHIfQ0pqhunlxM0wwWA5Pp1mQNASrbMIoc7Zb0Bv2TfHfOB3i8QmNEYXM4tKec8GPHT7Yw/v8ZPTWo8yGGA==,iv:qCWbuuXxRfOcTs8ZcKU/LkbURmw6acFoHof8/mUr/mw=,tag:r9YCuu1bAx6NeChqMAbbVQ==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNXlXaTlWSUNSWDN4OU04
            ZWhTZzVHRnZwelpMRWNjb0s5VnQxSnVKc1IwCkFxS2lRRWxTb3Joclh3SG93dU82
            M1R2T2FkS2Y1MzFVdnFndlI1MXhVaFUKLS0tIGs0bUFLbUJBZDQ0YzNKZTZ2RENL
            eldnZ09rQlRCbEVjRXNUUmZ6d2VZblEKVfSmpLtAe6FMMQRO0d2jeYOd6VCn5Dbx
            9Sx+21YURibzXQMoMGXvEI8J9uGVrMMzXucNCvZ2VWnbm2YVfY+ieQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T21:20:13Z"
    mac: ENC[AES256_GCM,data:QVkZBWSUSKEfg5gDsv5mYF6oBBPXyRutEEgJvNJKT8sF8u+bKSj9/0FciYDTl862nLBNzjD3qW74l2AWhtOry1yhAQPc24tiSascNBHSKyl9xYb75as1Nebql62+4adASpEtjS9VXdrusJTdUWLL4+QYiJDbhjGr5MiWD+I4rNI=,iv:N48RVJyvq3cCc90k3BnpukcL7YHvUupZlFWRmkpOR/U=,tag:h9tRT8fSazVbOzxCALX66A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
