---
core_kernel_modules:
  - rbd
  - nbd

rke2_type: server
rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_ha_mode_kubevip: false

rke2_servers_group_name: core_servers
rke2_agents_group_name: core_agents
rke2_cluster_group_name: core

rke2_version: v1.35.6+rke2r1
rke2_cni: calico
rke2_architecture: amd64

rke2_api_ip: "{{ hostvars[groups[rke2_servers_group_name][0]].ansible_host }}"
rke2_additional_sans: >-
  {{ (groups[rke2_servers_group_name]
      | map('extract', hostvars, 'ansible_host') | list)
     + [core_api_hostname] }}

rke2_server_node_taints: []

rke2_download_kubeconf: true
rke2_download_kubeconf_file_name: core.yaml
rke2_download_kubeconf_path: /tmp

rke2_token: "{{ lookup('env', 'RKE2_TOKEN') | mandatory }}"

rke2_custom_manifests:
  - "{{ playbook_dir }}/../files/rke2-ingress-nginx-config.yaml"
