apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:dzRLMcD1CzqnSuWSn5njh4lDDfZOXZlzdyL8g3p2tidjAA2R6pawhEc+lVq5Gcfkju/4bLQ=,iv:ZbclQjyY2ZwR6xzvL2D11cc97dYYm+nQGRHR8ZBer2Y=,tag:MYvZsYRBB+42Nxw3R+lx7A==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UkgzbGNtVVc5Y1JjdmI3
            bmNXOEcvZGtzME1meDRVZmV3S3drL0dTazM4ClBnTkxucXI0OFljS2NWZmcvejlV
            MDlSREM0V0FTdjJSd0w4Y0VIajBSYVEKLS0tIFA5TjYxVWFLMFlCZ2xlVVM0Tkl3
            cTBoNm4xaDQyVmtxTGRqUWdGNEE5UDgK0k/vWc7F6KF11PluaS+pd/TuqREr+XJX
            eKStc/WDsQuKSbTUz24FpRSbqeb8pnKQ7OFAaYgIUA2hZ+mPOX7oQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T19:16:57Z"
    mac: ENC[AES256_GCM,data:0I2J6+PwNr696AMHqGyNlm6+7fjnr3mulw+WIWOV3CZh3U/CkkU+Ij6ye2/FyBikGgBlCvuMVALdBl6u1J0Z1Y1vOrYdUAtQEWda3cgRDgsvm7qPZKmsLgl0qnvTGvNdqwL7xJXXf93yNWQN+KdW5tWXSm2MZsCToyCDSwAg/Ig=,iv:Yk2/eCtaNcV4nQqt8B3aisHP/UHY17g5QDNr/aXA+vQ=,tag:0WPnuB9szEFYgkZh/qB6KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
