apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
type: Opaque
stringData:
    METALLB_POOL_CIDR: ENC[AES256_GCM,data:8Yc6Jgli8CFY2bbtSYHu,iv:n0wZ5O5NkxI+7K0eP+WAoodRi1IiGWmBIs62XOfe3HQ=,tag:YTKT/M7MvrkZRtHMI33y8Q==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwalc0MUFZbXFKRzk2Mk1B
            dEkwVm54dEVabDkwejVnWGJLRHJPYkFNVG53CjA3US9rSkZscS9Hd1F6czZKbTFD
            SldhOGwrbHVORm52dCt5cVhpYnlTRXMKLS0tIDBZaG1PVjNqREcxMkE0dVpMcXcy
            U3VkS1dPRVZJSHhDbElyemlQaHowQTAKqkGjgnBHQTlOnjzUhE2GR38jCR5iQqZQ
            uHE8fcG+uMp+LP/NVhRQcY3wRMqyKeSMhQCfGxiOxE99RplbKYSP9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T03:10:51Z"
    mac: ENC[AES256_GCM,data:r0aSC7h2EZTul42wfukqgk1fLR9fGuLscuDCZDj2TfC4924fK7T5Yqqiyp+kOJHDthKlvFmA0916lKkYQkLT3mHN5SAny6ih00oo6IdPr2hT7p2GxuQkWs+6rWI/GxqPFslxuvGcmtHCUgSs3otupkN+Xh43f3BwfRrWZ1kC0NI=,iv:xgZQe2CA8obm9N/38c8uLIedem2YODAGra17hCXLZLM=,tag:GEbZel+8HWwu84ynxcd0TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
