apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:qdnoj+A=,iv:UWI548nQrb/6AQSDH+ImTwDCXYshzAXZUgr1AEG1M3I=,tag:2pLItW1Kng4O8KKabZGWBQ==,type:str]
    admin-password: ENC[AES256_GCM,data:+gdLAHaZ5NWCEkHOM6ZMZEfpcl4nu6CbGoLXybRavlC6oefbmugNeGZfVSiUnDui,iv:1KUdViblbvxQbvtjIhOM5ja51pA7ojroA+9y/MsZbIU=,tag:yNPjhkKj/NoOgWdb/T0O+A==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZXhzcm5mV083N1lka3Nj
            Y1pUMEdBQzdadlpPdEtsZ09IQ3BpbHdnU0VBClRzTlZRdXg5bmN0aVhZOG5QMitl
            b0xrYlZUc0ZjWFVrSmtFZ3B4bmpQVVEKLS0tIFNzR3J1dkFscmkweVAyTWpFN1Ni
            MlBUUHlPcXF1SEdmclFVVDBkSjYzc2cKnI5oIbMLNPNASKu5lZDm2LL2hMB7DICQ
            4oLJiKDkkiCaFCoKPnur5M4pQg+xv3hzpnuU6tX2RRLShA4E6scWOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T14:04:17Z"
    mac: ENC[AES256_GCM,data:jVn28UT85+8DQQa8vfFYytr+XusQsO3786O9DADVJc3tYNVEWvPR37L5bXjyPBTzowlfvtdptLIrdK//wlPvBAt7HgcwsEdg7AbyLALd0QXk+D1i9UHQYL7PkElfftbtgvUsnyvyTJdrQGEAkzmfddVSQvtX6BW9Q7oJfJPTk+Q=,iv:cL+V3m6XlYS8UIgc0d2tB3lsJ1V4G0V56YYDamuokVI=,tag:zWzy51wN6LEBuTK8Y73k1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
