apiVersion: v1
kind: Secret
metadata:
    name: vm-write-auth
    namespace: monitoring
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:d9MWwsHn0NRTFupsIOKOvYb1yxTWoiVfirRlSkZoey/EbfLp6bD9/wCTVtk1mdgKqyVoY79tNXBy32SF3lbmKl1oMACNYeXEPMw=,iv:QwjWhVENbvie+48bRnMaY5Wbzyb8rhpHKEa4YGzRP+k=,tag:qlqANJT9rD+EO+CJoKCcNQ==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWVBqdERxdm96M0Zya25j
            clFHQ2JsRE1vUTFPbEZxeW5HY1FWNG5vdW1nClhycFBac1hpU3FDSnBhNWxXQ1I0
            U1c0N05jaElHK0IrUnh0R1JaalgySUEKLS0tIDRtOWJCeXZZYXdtYzdpRFFaMFB2
            NHRuNEU2SFFuZmNDcDBKeCtXV1czTU0KRg2O3yj+qBadSp0H7kpWr9cn4F+pofiv
            f1ivLbv8fbDXLUzPRhtLrnyyjGxB5cY066hJxh3vhPsfl+418RMF+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T23:18:38Z"
    mac: ENC[AES256_GCM,data:KHc1CNI5dMR4kcL1BRTJI3tzq3rS9xwr1SgZHZhcB9jDsD1idOiX6VxDZMX3Ug9C9q9lOlpytXuAZ8BKUxtzwzBgI89QHFpErunoQ8FXbmAefABRmAXL16cATJDw9lHgYY+yx9xljLL5VAqvHFlew4fHfQ0X84VQB4dlN7zLikY=,iv:pfSiHUFmuaybPnZIgr5786B1WyrpjXm05TkYE8Cqiho=,tag:zieJAEHo/VEMLxFKkWvIFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
