---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vm-write
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: vm-write-auth
    nginx.ingress.kubernetes.io/auth-realm: "core telemetry ingest"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.120.0.0/24,10.120.1.0/24"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  ingressClassName: nginx
  rules:
    - host: telemetry.core.stplabs.io
      http:
        paths:
          - path: /api/v1/write
            pathType: Prefix
            backend:
              service:
                name: victoriametrics-victoria-metrics-single-server
                port:
                  number: 8428
          - path: /api/v2/alerts
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-alertmanager
                port:
                  number: 9093
          - path: /loki/api/v1/push
            pathType: Prefix
            backend:
              service:
                name: loki
                port:
                  number: 3100
  tls:
    - hosts:
        - telemetry.core.stplabs.io
      secretName: telemetry-tls
