apiVersion: v1
kind: Secret
metadata:
    name: vm-write-auth
    namespace: monitoring
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:+IC2QCH8P3gI6b9dwWAh6d+R9Sq6PjBvxpVVSkCtVE7tqZxDyo1OIiTf,iv:8MvKX73K+lHoSmtKlj628S2HQP8TIkS/4Gy4YT4FpDg=,tag:oTdjxQ/yxcJRdmOyeZ5JHA==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWVBqdERxdm96M0Zya25j
            clFHQ2JsRE1vUTFPbEZxeW5HY1FWNG5vdW1nClhycFBac1hpU3FDSnBhNWxXQ1I0
            U1c0N05jaElHK0IrUnh0R1JaalgySUEKLS0tIDRtOWJCeXZZYXdtYzdpRFFaMFB2
            NHRuNEU2SFFuZmNDcDBKeCtXV1czTU0KRg2O3yj+qBadSp0H7kpWr9cn4F+pofiv
            f1ivLbv8fbDXLUzPRhtLrnyyjGxB5cY066hJxh3vhPsfl+418RMF+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T22:07:22Z"
    mac: ENC[AES256_GCM,data:yFaEalTP2nNEHJNd898kCml3fVYmA7BgwvSWADis3tBo2UwsxHACv+2gDZKmj9ZkpFgWFguzQc/X+YygNJFKCv3Ng+HNNh5dznBqr7ehxT3AELy9pMUqs1CW/v3Ft3VZLwgW5X3PWMzrcOsm4j3SDifeVPLq44HFDPSgstSzfgw=,iv:dcmEqPd9qTOisU7cj8CK776RTeWU4PEJxzlUy7HGXdQ=,tag:9P2N8f/VfTfpewG/O8krIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
