---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.sops.yaml
  - db-backup-s3-creds.sops.yaml
  - oidc-secret.sops.yaml
  - cnpg-cluster.yaml
  - helmrelease.yaml
