apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc-secret
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:8aNnayhhtrXCwK3WyikVA+GCGpbIBTkpe5VpLHX8s6E=,iv:XEhPJtcS1yD7K+D2pMx4HFhFriHHgfxQzYh96IaFZQo=,tag:xOjCr/sCPZz1eTYNtHZ0Kw==,type:str]
    secret: ENC[AES256_GCM,data:ykIfT7EObbNuPCulIIJF60kvCc3tmkMeQ9o43jyMqpxVY0DkRbmTpqs4XMjTH83jBaYUx/T0WOGyNRr4DGHAZQ==,iv:F2axX7+rc0J2W4gAqCQcGlppbzAeoyg2s6NDnIInRBY=,tag:S0E/BZnQGf69UEe6FZNvNw==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4akdXZWU4YktGSWl6NDUv
            TEF4MXUxUkhKY1BybElPZk1HRnVQbko2L0NFClY5VStvZ00rN3BZOTJTd0xOWHZq
            ZHRlbHd6UUNTVzVJZnVPTzVvRE5Cd2MKLS0tIHJXTzlPbW1hcUFRNDJpckxIMzE0
            ZEUwMHhiYkRxbzlueHg3S2xlMmxFUHcKFJzQo3RHDsO46xPIRDabfzrFWTuP6idE
            pfnTop5r3Yq9e+StvNRzEhOtoWXAG8txM331fRrqTw/3tVA/FTpc6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T04:34:59Z"
    mac: ENC[AES256_GCM,data:Mn04ArrJJp8P/LcXi5w3eXLIpEk91gjfTjHSi6A3ZerfmLiWv/82Z6Btk3+1M1OcBw+3X4TLjdKcKwl5lLyvfEk+Vt2OqLozWalCdomNsRYclLBQ4IoZ1XkeI1Alx7Rw8ERWqg78i5QPwNhTFoiMBX4p9I/88ghfWHk4htvyAMM=,iv:fz25V/9BqEhElJSZiCMjHG6KccipkU7EX8WCoeCeYy8=,tag:ko0YUzdyungJmT/jyXbWPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
