apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc-secret
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:8aNnayhhtrXCwK3WyikVA+GCGpbIBTkpe5VpLHX8s6E=,iv:XEhPJtcS1yD7K+D2pMx4HFhFriHHgfxQzYh96IaFZQo=,tag:xOjCr/sCPZz1eTYNtHZ0Kw==,type:str]
    secret: ENC[AES256_GCM,data:dR7t0RRQteHtPOSrMrFrDOiTsCe/eNFduPgi8I1qdOVgu9yB2cze/fopsOpEtobHBDbrJJzsHq7iqV1I8tVIqw==,iv:/syGjVLLBXkhHAs5THonkZQXzPGMa2E9GzFOxSci5r8=,tag:iw0HiuWn8ZJeRWaycSeXgg==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4akdXZWU4YktGSWl6NDUv
            TEF4MXUxUkhKY1BybElPZk1HRnVQbko2L0NFClY5VStvZ00rN3BZOTJTd0xOWHZq
            ZHRlbHd6UUNTVzVJZnVPTzVvRE5Cd2MKLS0tIHJXTzlPbW1hcUFRNDJpckxIMzE0
            ZEUwMHhiYkRxbzlueHg3S2xlMmxFUHcKFJzQo3RHDsO46xPIRDabfzrFWTuP6idE
            pfnTop5r3Yq9e+StvNRzEhOtoWXAG8txM331fRrqTw/3tVA/FTpc6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T03:11:46Z"
    mac: ENC[AES256_GCM,data:0tcG+3FU2eAjRfWE3DGcDZMRUQGpEYYUiWZJkWtKBscAu2bwJGXk5gfping3eYDSCEvibUALG/Cm8fer2LfMIOVDl/ZrMFjaDwJlXtlGnUUPR9XANfrpN0V3BOoHB8NLlyYnroc4Szk+f8E/efxL1E9Jo8r9zPBNb7rEWiXTvLM=,iv:aOMS1R7siusse7P2VDghkhCySeW5EAiDIikUjFIZEwE=,tag:BfZpUlIFu+LpSFSdlmRWzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
