apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:i/7XlUU=,iv:Lgc1/U1cVnb71TCrTJRCkScBCZomvCBw5b1o38ecHa4=,tag:il+ZtNSfntuOGEsj93P/eA==,type:str]
    password: ENC[AES256_GCM,data:DwVxBltB2btITLMpWCyU9MVn6vjp3gU6jrO1RUHkOwLRrZ5ar6flZD28e0s2XmIcMlJB6g==,iv:HA7A6V/XWkrM8D4x/r8xSC2NJghfILvxtWxIaUsm+GM=,tag:RIOKMBLzMWcFowyL4rVezg==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQzVYaGVYa2d5WTEzRXpO
            QTdQK1Qzc01UT0NLRStMQUUxM1NiVWZ5V1JVCnVOT1lteTRkWHV5TytZcVpaOGlN
            Y1JwWFR3eUVkNjJlL3ZjaDBnZWxETzQKLS0tIGF0QkhFWTJUVjFRMjgvK2xMNWpZ
            MWs5Q2Y4aGc1SWRKQXpUem1MZ2J2a1UKGulpcIQuApquwPnCj1zuHTi4H6O/YVUj
            UczziMxsvFwrijXosus4/bnRUD48Q/TEO5QLrHx5h7qINKa/sxEVYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T01:08:16Z"
    mac: ENC[AES256_GCM,data:sEZ09Q0pzyPYH34GahyDCul15xwaj24jTohj3vz0Z6bMoR8anJRGLF/Xiwf33r7HZZB+l985Sk1ll2CWbf8/Uc72L2yBNzkicThlalScDYsNJiCL1VaZsWuK7zdsnTXmMqt+wEEHtSw5zZYl5mASlgbUrRSp7jES8xB6UpaGQJI=,iv:NiU/wtP0m3EAFBNyW/2D2gZyuqmtu2MSR6CKU+Sd+xo=,tag:/SbJEklxVPLAMKTij0N96w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
