apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:NjNevUG6K8mbu4lQOA==,iv:N3h3/BJCBm0Mz7JFYNlsKtSA8WMzF2tbtnLRYMunyKo=,tag:GBXTg7LfWeUnUXiRte9Btw==,type:str]
    password: ENC[AES256_GCM,data:6Iy9afpA9AEcbGWjrOeX5uuUmE1aDpr0pDGal+GoVbz+mtPAU9CynrO2wdCN8KxNv5NggA==,iv:gWJT2MoCLLvhXYjj0XLalgIvR342AbcjsNl5PdwtwQg=,tag:ruvzfRdC0RIs7QTH6HsRBQ==,type:str]
sops:
    age:
        - recipient: age15w65euzcyg3c3zltzd3t97tlqrq2d9c0ufltvjrwuh0geelgacwqkd7cxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVVBqa3M4SG1jdVcwQ1My
            Nk03VUZxNk9yOFl3dmVZQytqUFBMMEtKNmo0CkpHdktHblFEakI5MnkxejdZVlBP
            eTNJODIzZ2hvbGhHK0pHdlE3bWRvTmcKLS0tIHNIVVB5RUtGSm45cHRiU1RPTUlT
            Q09oUUszWjJTQm83c29NenVQSWJ1S1kK8W8KsuAWEAuw5l6zNFwJ9RpUsjuvb9l3
            ZzSvl8KtXupWqftVqJPPC3sUOigqrtSr8gTRHa/gQ1PBcAtUFN4n5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T01:28:56Z"
    mac: ENC[AES256_GCM,data:0P+TtxcVCCcJHtkXbLxjHTQkze+va3uQaqfDu4SKJB4Ni2MicaovnvSgjZpdxi74YvbUiOYNOB7Gbs7pdX2d00W8UKTPjnKYsbw2zKSPuCdH2puohPuBTj27JaD3nQLhtIf7ra8QSR8cb2jWwVegv0Jz4ruVVk2LACqKJC/F+1A=,iv:SKx0MT+veTHrcw37dU80leAcBTji376tmry31agb9+Y=,tag:sbVmN3rq2Sg402bnK4bLbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
